// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockStorageInterface is an autogenerated mock type for the StorageInterface type
type MockStorageInterface struct {
	mock.Mock
}

type mockConstructorTestingTNewMockStorageInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockStorageInterface creates a new instance of MockStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStorageInterface(t mockConstructorTestingTNewMockStorageInterface) *MockStorageInterface {
	mock := &MockStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
